aci:
  "ACCESS": 0
  "LOMAX": 1
  "LOMAX PRO": 2
  "ACI": 0
  "ADARAC": 0
  "ROCKSTAR": 0
  "SNOWSPORT": 0

tech:
  "Underseat Storage System": 0
  "Front&Rear Side Window Deflectors": 1
  "Rear FloorLiner": 2
  "Rear FloorLiner for vinyl floors": 2
  "Front FloorLiner": 2
  "Front FloorLiner HP": 2
  "Rear FloorLiner HP": 2
  "Rear Rubber Mats": 3
  "Front Rubber Mats": 3
  "Cargo Liners": 4
  "Cargo With Bumper Protector": 4
  "LampGard": 6
  "SunShade": 8
  "SunShade Full Vehicle Kit": 8

warn:
  "120V MOTOR": 0
  "230V MOTOR": 0
  "12V MOTOR KIT": 0
  "12V MOTOR": 0
  "200V MOTOR": 0
  "24V MOTOR": 0
  "4XFLARES": 0
  "ABRASION GUARD": 0
  "ABRASION SLEEVE": 0
  "AC MOTOR": 0
  "ACCESSORY KIT": 0
  "ACTUATOR": 0
  "ADAPTER  ": 0
  "ADAPTER KIT": 0
  "ADAPTER PLATE": 0
  "AIR CLUTCH KIT": 0
  "AIR CLUTCH": 0
  "ANCHOR": 0
  "ASSORTMENT": 0
  "BACKING PLATE": 0
  "BACKPACK": 0
  "BADGE KIT": 0
  "BAG": 0
  "BALL BEARING": 0
  "BASE PLATE": 0
  "BATTERY LEAD": 0
  "BATTERY": 0
  "BEARING ASSEMBLY": 0
  "BELT": 0
  "BLADE SIDE": 0
  "BOLT KIT": 0
  "BOLT": 0
  "BOOSTER CABLE KIT": 0
  "BOOT KIT": 0
  "BRACKET KIT": 0
  "BRACKET": 0
  "BRACKETS": 0
  "BRAKE AND PAWL ASSY": 0
  "BRAKE ASSEMBLY": 0
  "BRAKE ASSY": 0
  "BRAKE KIT": 0
  "BRAKE LINING": 0
  "BRAKE PUCK": 0
  "BRAKE SERVICE KIT": 0
  "BRAKE SHAFT": 0
  "BRAKE": 0
  "BRUSH PLATE": 0
  "BRUSH SET W/HOLDER": 0
  "BRUSHES": 0
  "BUCKET KIT": 0
  "BULB": 0
  "BUMPER BRACKETS": 0
  "BUMPER GUARD": 0
  "BUMPER KIT": 0
  "BUSHING AND SEAL KIT": 0
  "BUSHING KIT": 0
  "BUSHING": 0
  "BUSS BARS": 0
  "CABLE ASSEMBLY": 0
  "CABLE CONNECTOR 16'": 0
  "CABLE KIT": 0
  "CABLE POWER 90\"": 0
  "CABLE STOP": 0
  "CABLE": 0
  "CAM": 0
  "CAPSCREW": 0
  "CARRIER ASSEMBLY": 0
  "CARRIER ASSY": 0
  "CENTER CAP": 0
  "CHARGER ": 0
  "CHARGER": 0
  "CLAMPS": 0
  "CLEVIS": 0
  "CLUTCH ASSEMBLY": 0
  "CLUTCH BLOCK-OUT": 0
  "CLUTCH DIAL": 0
  "CLUTCH KNOB": 0
  "CLUTCH LEVER  ": 0
  "CLUTCH LEVER": 0
  "CLUTCH PIN": 0
  "CLUTCH RETURN SPRING": 0
  "CLUTHC ASSEMBLY": 0
  "CONTACTOR  ": 0
  "CONTACTOR PLATE": 0
  "CONTACTOR": 0
  "CONTROL HOUSING": 0
  "CONTROL MODULE": 0
  "CONTROL PACK BRACKET": 0
  "CONTROL PACK COVER": 0
  "CONTROL PACK": 0
  "CONVERSION KIT": 0
  "COUPLER ": 0
  "COUPLER HOOK": 0
  "COUPLER": 0
  "COVER  ": 0
  "COVER": 0
  "COVER-WINCH": 0
  "CRANKCASE ASSEMBLY": 0
  "CYLINDER HEAD": 0
  "DAMPER": 0
  "DECAL": 0
  "DETENT SPACER": 0
  "DISC BRAKE ASSEMBLY": 0
  "DISC BRAKE": 0
  "DISCONNECT": 0
  "DISK BRAKE ASSEMBLY": 0
  "DISK BRAKE": 0
  "DOWEL PIN": 0
  "DRILL WINCH": 0
  "DRIVE PIN": 0
  "DRIVE SHAFT": 0
  "DRIVESHAFT": 0
  "DRUM AND BRAKE": 0
  "DRUM ASSEMBLY": 0
  "DRUM BUSHING": 0
  "DRUM KIT": 0
  "DRUM MASK": 0
  "DRUM RETARDER": 0
  "DRUM SUPPORT KIT": 0
  "DRUM SUPPORT": 0
  "DRUM": 0
  "DUFFLE BAG": 0
  "DUST CAP": 0
  "DUST COVER": 0
  "ELECTRICAL CONNECTOR": 0
  "EMBLEM": 0
  "END CAP": 0
  "END HOUSING": 0
  "END SUPPORT ASSY": 0
  "EXTENSION": 0
  "EYELET": 0
  "FAIRLEAD ASSEMBLY": 0
  "FAIRLEAD COVER": 0
  "FAIRLEAD MOUNT": 0
  "FAIRLEAD PLATE": 0
  "FAN": 0
  "FASTENER KIT  ": 0
  "FASTENER KIT": 0
  "FIRE EXT HOLDER": 0
  "FOLLOWER CAM ": 0
  "FORGED FAIRLEAD": 0
  "FRONT BUMPER": 0
  "FRONT RECEIVER": 0
  "GASKET": 0
  "GEAR END ASSEMBLY": 0
  "GEAR HOUSING": 0
  "GEAR KIT": 0
  "GEARTRAIN": 0
  "GLOVES": 0
  "GRAB HANDLE": 0
  "GRILLE GUARD KIT": 0
  "GRILLE GUARD": 0
  "HANDLE": 0
  "HARDWARE KIT": 0
  "HARDWARE PACK": 0
  "HARNESS": 0
  "HAWSE FAIRLEAD": 0
  "HEADLAMP GUARDS": 0
  "HEX SHAFT": 0
  "HITCH MOUNT": 0
  "HITCH PIN": 0
  "HOIST": 1
  "HOLSTER": 0
  "HOOK KIT": 0
  "HOOK STRAP": 0
  "HOOK": 0
  "HOUSING": 0
  "HUB CONVERSION KIT": 0
  "HUB SERVICE KIT": 2
  "HYDRAULIC HOSE": 0
  "HYDRAULIC MANIFOLD": 0
  "HYDRAULIC MOTOR": 0
  "HYDRAULIC VALVE": 0
  "HYPERLINK": 0
  "INPUT GEAR": 0
  "INTERCOOLER ": 0
  "INTERMEDIATE GEAR": 0
  "ISOLATOR": 0
  "J-BOLT KIT": 0
  "JACK MOUNT": 0
  "LABEL  ": 0
  "LABEL KIT": 0
  "LABEL": 0
  "LATCH KIT": 0
  "LATCH": 0
  "LIGHT BAR": 0
  "LIGHT BEZEL": 0
  "LIGHT INSERT": 0
  "LIGHTBAR": 0
  "LOAD LIMITER": 0
  "LOCK WASHER": 0
  "LOCKING HUBS": 2
  "LOWER HOUSING KIT": 0
  "LOWER HOUSING": 0
  "MAIN GEAR": 0
  "MANUAL CLUTCH ASSY": 0
  "MANUAL CLUTCH": 0
  "MICROSWITCH": 0
  "MOTOR  ": 0
  "MOTOR COVER": 0
  "MOTOR END CAP": 0
  "MOTOR KIT": 0
  "MOTOR": 0
  "MOUNT ": 0
  "MOUNT": 0
  "MOUNTING KIT": 0
  "MOUNTING PLATE KIT": 0
  "MULTIMOUNT KIT": 0
  "NAMEPLATE": 0
  "NEEDLE BEARING": 0
  "NUT": 0
  "O RING": 0
  "O-RING": 0
  "OVERLOAD INTERUPT": 0
  "PARTS PACK": 0
  "PIN  ": 0
  "PIN W/SAFETY RETAINR": 0
  "PINION & CAM": 0
  "PINION AND CAM": 0
  "PINION GEAR": 0
  "PISTON ASSEMBLY": 0
  "PIVOT ASSEMBLY": 0
  "PIVOT KIT": 0
  "PLATE": 0
  "PLOW ASSEMBLY": 0
  "PLOW BLADE": 0
  "PLOW BRACKET KIT": 0
  "PLOW CONTROL": 0
  "PLOW FRAME": 0
  "PLOW HARDWARE KIT": 0
  "PLOW KIT": 0
  "PLOW MARKER KIT": 0
  "PLOW MOUNT KIT": 0
  "PLOW SKID KIT": 0
  "PLOW SKIDS": 0
  "PLOW SPRING": 0
  "PLOW STRAP KIT": 0
  "PLOW STRAP": 0
  "PLOW TOP FLAP": 0
  "PLOW WEAR STRIP ": 0
  "PLOW WIRE ROPE": 0
  "PLUG": 0
  "PORTABLE ANCHOR ": 0
  "POWER INTERUPT": 0
  "PROTECTOR": 0
  "PULLEY  ": 0
  "PULLZALL ": 0
  "QUICK RELEASE": 0
  "RADIAL OIL SEAL": 0
  "RADIAL SEAL": 0
  "RATCHET": 0
  "REAR BUMPER": 0
  "RECEIVER  ": 0
  "RECEIVER SHACKLE": 0
  "RECEPTACLE": 0
  "RECIEVER PLUG": 0
  "RECOVERY STRAP": 0
  "RELAY": 0
  "RELOCATION KIT": 0
  "REMOTE CLUTCH": 0
  "REMOTE CONTROL": 0
  "REMOTE HOLDER": 0
  "REMOTE KIT": 0
  "REMOTE SOCKET": 0
  "REMOTE SWITCH": 0
  "REPAIR KIT": 0
  "REPLACEMENT PIN": 0
  "RETAINER": 0
  "RETAINING RING": 0
  "RETROFIT KIT": 0
  "RETURN SPRING": 0
  "RIGGING KIT ": 0
  "RIGGING STRAP": 0
  "RING GEAR": 0
  "ROCK SLIDERS": 0
  "ROLLER FAIRLEAD": 0
  "ROLLER SHAFT": 0
  "ROLLER": 0
  "ROPE ANCHOR": 0
  "ROPE COVER": 0
  "ROPE GUIDE": 0
  "RUBBER PLUG": 0
  "SAFETY CLIP": 0
  "SAFTEY HOOK W/STRAP": 0
  "SCREW": 0
  "SEAL ": 0
  "SEAL KIT": 0
  "SEALING WASHER": 0
  "SERIES WINCH": 0
  "SERVICE KIT": 0
  "SET SCREW": 0
  "SEVERE DUTY WINCH": 0
  "SHACKLE ": 0
  "SHACKLE BRACKET": 0
  "SHACKLE": 0
  "SHAFT": 0
  "SHIFT KNOB": 0
  "SIDE GEAR": 0
  "SIDE MEMBER": 0
  "SIDEWINDER": 0
  "SKID PLATE": 0
  "SKIRTING KIT": 0
  "SLING": 0
  "SNAP PIN": 0
  "SNATCH BLOCK": 0
  "SOCKET ASSEMBLY": 0
  "SOCKET ASSY": 0
  "SOCKET KIT": 0
  "SOCKET": 0
  "SOFT SHACKLE": 0
  "SOLENOID ": 0
  "SOLENOID BRACKET": 0
  "SOLENOID HOUSING": 0
  "SOLENOID PACK": 0
  "SOLENOID": 0
  "SPACER  ": 0
  "SPACER": 0
  "SPLINED DRIVE GEAR": 0
  "SPRING  ": 0
  "SPRING ANCHOR": 0
  "SPRING": 0
  "SPRINGS": 0
  "STEEL BALL": 0
  "STEELBALL": 0
  "STORAGE BAG": 0
  "STRAP": 0
  "STUD KIT": 0
  "SUN GEAR": 0
  "SWITCH": 0
  "SWIVEL": 0
  "SYN ROPE SVC KIT": 0
  "SYNTHETIC ROPE EXTEN": 0
  "SYNTHETIC ROPE": 0
  "TENSION PLATE": 0
  "TENSION SPRING": 0
  "TENSIONER  ": 0
  "TENSIONER KIT": 0
  "TERMINAL DUST COVER": 0
  "TERMINAL KIT": 0
  "THERMAL SWITCH": 0
  "THRUST WASHER": 0
  "TIE BAR": 0
  "TIE BOLT": 0
  "TIE PLATE": 0
  "TIE ROD ": 0
  "TIE ROD": 0
  "TIRE CARRIER  ": 0
  "TIRE CARRIER": 0
  "TIRE DELETE PLATE": 0
  "TORSION SPRING": 0
  "TOW HOOK-BLACK": 0
  "TOW HOOK-CHROME": 0
  "TOW POINTS": 0
  "TRAILER WINCH PLATE": 0
  "TRANSMISSION": 0
  "TRANSMITTER": 0
  "TUBE ASSEMBLY": 0
  "TUBE DOORS": 0
  "U-BOLT": 0
  "UPGRADE KIT": 0
  "UPPER HOUSING": 0
  "VALVE": 0
  "WASHER": 0
  "WASHERS": 0
  "WEAR BAR": 0
  "WHEEL": 0
  "WINCH CARRIER": 0
  "WINCH COVER": 0
  "WINCH FRAME": 0
  "WINCH KIT": 0
  "WINCH MOUNTING KIT": 0
  "WINCH SUBASSEMBLY": 0
  "WINCH": 1
  "WIRE HARNESS": 0
  "WIRE KIT": 0
  "WIRE ROPE ASSEMBLY": 0
  "WIRE ROPE EXTENSION": 0
  "WIRE ROPE KIT": 0
  "WIREROPE ASSEMBLY": 0
  "WIRING KIT": 0
