# Import vender functions

def vendor_func(vendor_name):
	if vendor_name == "tech":
	    import vendor.tech as vendor
	elif vendor_name == "aci":
	    import vendor.aci as vendor
	elif vendor_name == "adu":
	    import vendor.adu as vendor
	elif vendor_name == "airl":
	    import vendor.airl as vendor
	elif vendor_name == "and":
	    import vendor.andd as vendor
	elif vendor_name == "anz":
	    import vendor.anz as vendor
	elif vendor_name == "amp":
	    import vendor.amp as vendor
	elif vendor_name == "ampm":
	    import vendor.ampm as vendor
	elif vendor_name == "aor":
	    import vendor.aor as vendor
	elif vendor_name == "arb":
	    import vendor.arb as vendor
	elif vendor_name == "arcl":
	    import vendor.arcl as vendor
	elif vendor_name == "ard":
	    import vendor.ard as vendor
	elif vendor_name == "bak":
	    import vendor.bak as vendor
	elif vendor_name == "baja":
	    import vendor.baja as vendor
	elif vendor_name == "bap":
	    import vendor.bap as vendor
	elif vendor_name == "best":
	    import vendor.best as vendor
	elif vendor_name == "big":
	    import vendor.big as vendor
	elif vendor_name == "bigm":
	    import vendor.bigm as vendor
	elif vendor_name == "bkr":
	    import vendor.bkr as vendor
	elif vendor_name == "brm":
	    import vendor.brm as vendor
	elif vendor_name == "btr":
	    import vendor.btr as vendor
	elif vendor_name == "bush":
	    import vendor.bush as vendor
	elif vendor_name == "buy":
	    import vendor.buy as vendor
	elif vendor_name == "tim":
	    import vendor.tim as vendor
	elif vendor_name == "carr":
	    import vendor.carr as vendor
	elif vendor_name == "cbp":
	    import vendor.cbp as vendor
	elif vendor_name == "cipa":
	    import vendor.cipa as vendor
	elif vendor_name == "crg":
	    import vendor.crg as vendor
	elif vendor_name == "cog":
	    import vendor.cog as vendor
	elif vendor_name == "curt":
	    import vendor.curt as vendor
	elif vendor_name == "deck":
	    import vendor.deck as vendor
	elif vendor_name == "dez":
	    import vendor.dez as vendor
	elif vendor_name == "eccot":
	    import vendor.eccot as vendor
	elif vendor_name == "eccon":
	    import vendor.eccon as vendor
	elif vendor_name == "ele":
	    import vendor.ele as vendor
	elif vendor_name == "ext":
	    import vendor.ext as vendor
	elif vendor_name == "ffi":
	    import vendor.ffi as vendor
	elif vendor_name == "fia":
	    import vendor.fia as vendor
	elif vendor_name == "fil":
	    import vendor.fil as vendor
	elif vendor_name == "fire":
	    import vendor.fire as vendor
	elif vendor_name == "fpm":
	    import vendor.fpm as vendor
	elif vendor_name == "gor":
	    import vendor.gor as vendor
	elif vendor_name == "gorm":
	    import vendor.gorm as vendor
	elif vendor_name == "hus":
	    import vendor.hus as vendor
	elif vendor_name == "kar":
	    import vendor.kar as vendor
	elif vendor_name == "kc":
	    import vendor.kc as vendor
	elif vendor_name == "kln":
	    import vendor.kln as vendor
	elif vendor_name == "knk":
	    import vendor.knk as vendor
	elif vendor_name == "knkm":
	    import vendor.knkm as vendor
	elif vendor_name == "knn":
	    import vendor.knn as vendor
	elif vendor_name == "lift":
	    import vendor.lift as vendor
	elif vendor_name == "lnd":
	    import vendor.lnd as vendor
	elif vendor_name == "luv":
	    import vendor.luv as vendor
	elif vendor_name == "mas":
	    import vendor.mas as vendor
	elif vendor_name == "mass":
	    import vendor.mass as vendor
	elif vendor_name == "mba":
	    import vendor.mba as vendor
	elif vendor_name == "mrw":
	    import vendor.mrw as vendor
	elif vendor_name == "mrwm":
	    import vendor.mrwm as vendor
	elif vendor_name == "myp":
	    import vendor.myp as vendor
	elif vendor_name == "nfa":
	    import vendor.nfa as vendor
	elif vendor_name == "rgr":
	    import vendor.rgr as vendor
	elif vendor_name == "nitro":
	    import vendor.nitro as vendor
	elif vendor_name == "rch":
	    import vendor.rch as vendor
	elif vendor_name == "rnl":
	    import vendor.rnl as vendor
	elif vendor_name == "road":
	    import vendor.road as vendor
	elif vendor_name == "rrk":
	    import vendor.rrk as vendor
	elif vendor_name == "rsp":
	    import vendor.rsp as vendor
	elif vendor_name == "kso":
	    import vendor.kso as vendor
	elif vendor_name == "odr":
	    import vendor.odr as vendor
	elif vendor_name == "ovs":
	    import vendor.ovs as vendor
	elif vendor_name == "par":
	    import vendor.par as vendor
	elif vendor_name == "piaa":
	    import vendor.piaa as vendor
	elif vendor_name == "prime":
	    import vendor.prime as vendor
	elif vendor_name == "protec":
	    import vendor.protec as vendor
	elif vendor_name == "put":
	    import vendor.put as vendor
	elif vendor_name == "qf":
	    import vendor.qf as vendor
	elif vendor_name == "rcs":
	    import vendor.rcs as vendor
	elif vendor_name == "rdl":
	    import vendor.rdl as vendor
	elif vendor_name == "rfn":
	    import vendor.rfn as vendor
	elif vendor_name == "rig":
	    import vendor.rig as vendor
	elif vendor_name == "rlg":
	    import vendor.rlg as vendor
	elif vendor_name == "rtx":
	    import vendor.rtx as vendor
	elif vendor_name == "rug":
	    import vendor.rug as vendor
	elif vendor_name == "sb":
	    import vendor.sb as vendor
	elif vendor_name == "scs":
	    import vendor.scs as vendor
	elif vendor_name == "sls":
	    import vendor.sls as vendor
	elif vendor_name == "snow":
	    import vendor.snow as vendor
	elif vendor_name == "stlc":
	    import vendor.stlc as vendor
	elif vendor_name == "tft":
	    import vendor.tft as vendor
	elif vendor_name == "trux":
	    import vendor.trux as vendor
	elif vendor_name == "truxm":
	    import vendor.truxm as vendor
	elif vendor_name == "und":
	    import vendor.und as vendor
	elif vendor_name == "uws":
	    import vendor.uws as vendor
	elif vendor_name == "uwsb":
	    import vendor.uwsb as vendor
	elif vendor_name == "ven":
	    import vendor.ven as vendor
	elif vendor_name == "vms":
	    import vendor.vms as vendor
	elif vendor_name == "warn":
	    import vendor.warn as vendor
	elif vendor_name == "wes":
	    import vendor.wes as vendor
	elif vendor_name == "west":
	    import vendor.west as vendor
	elif vendor_name == "yak":
	    import vendor.yak as vendor
	elif vendor_name == "zll":
	    import vendor.zll as vendor
	elif vendor_name == "t-rex":
	    import vendor.trex as vendor
	elif vendor_name == "trm":
	    import vendor.trm as vendor
	elif vendor_name == "und":
	    import vendor.und as vendor
	elif vendor_name == "uws":
	    import vendor.uws as vendor
	elif vendor_name == "uwsb":
	    import vendor.uwsb as vendor
	elif vendor_name == "ven":
	    import vendor.ven as vendor
	elif vendor_name == "vms":
	    import vendor.vms as vendor
	elif vendor_name == "warn":
	    import vendor.warn as vendor
	elif vendor_name == "wes":
	    import vendor.wes as vendor
	elif vendor_name == "west":
	    import vendor.west as vendor
	elif vendor_name == "yak":
	    import vendor.yak as vendor
	elif vendor_name == "zll":
	    import vendor.zll as vendor

	return vendor
