# Import vender functions

def vendor_func(vendor_name):
	if vendor_name == "tech":
	    import vendor.tech as vendor
	elif vendor_name == "aci":
	    import vendor.aci as vendor
	elif vendor_name == "ard":
	    import vendor.ard as vendor
	elif vendor_name == "adu":
	    import vendor.adu as vendor
	elif vendor_name == "amp":
	    import vendor.amp as vendor
	elif vendor_name == "baja":
	    import vendor.baja as vendor
	elif vendor_name == "big":
	    import vendor.big as vendor
	elif vendor_name == "bkr":
	    import vendor.bkr as vendor
	elif vendor_name == "buy":
	    import vendor.buy as vendor
	elif vendor_name == "tim":
	    import vendor.tim as vendor
	elif vendor_name == "carr":
	    import vendor.carr as vendor
	elif vendor_name == "curt":
	    import vendor.curt as vendor
	elif vendor_name == "deck":
	    import vendor.deck as vendor
	elif vendor_name == "eccot":
	    import vendor.eccot as vendor
	elif vendor_name == "eccon":
	    import vendor.eccon as vendor
	elif vendor_name == "fia":
	    import vendor.fia as vendor
	elif vendor_name == "gor":
	    import vendor.gor as vendor
	elif vendor_name == "gorm":
	    import vendor.gorm as vendor
	elif vendor_name == "kar":
	    import vendor.kar as vendor
	elif vendor_name == "knk":
	    import vendor.knk as vendor
	elif vendor_name == "knn":
	    import vendor.knn as vendor
	elif vendor_name == "nfa":
	    import vendor.nfa as vendor
	elif vendor_name == "rch":
	    import vendor.rch as vendor
	elif vendor_name == "road":
	    import vendor.road as vendor
	elif vendor_name == "rrk":
	    import vendor.rrk as vendor
	elif vendor_name == "rsp":
	    import vendor.rsp as vendor
	elif vendor_name == "kso":
	    import vendor.kso as vendor
	elif vendor_name == "odr":
	    import vendor.odr as vendor
	elif vendor_name == "par":
	    import vendor.par as vendor
	elif vendor_name == "piaa":
	    import vendor.piaa as vendor
	elif vendor_name == "prime":
	    import vendor.prime as vendor
	elif vendor_name == "protec":
	    import vendor.protec as vendor
	elif vendor_name == "rig":
	    import vendor.rig as vendor
	elif vendor_name == "scs":
	    import vendor.scs as vendor
	elif vendor_name == "trux":
	    import vendor.trux as vendor
	elif vendor_name == "vms":
	    import vendor.vms as vendor
	elif vendor_name == "warn":
	    import vendor.warn as vendor
	elif vendor_name == "wes":
	    import vendor.wes as vendor
	elif vendor_name == "west":
	    import vendor.west as vendor
	elif vendor_name == "yak":
	    import vendor.yak as vendor

	return vendor
